### ISSUE TITLE
Bug: Variable Declarations after function calls lead to incorrect leakage computation?

### ISSUE THREAD

**Issue by tnstrssnr** [parttimenerd/nildumu#3]
Hi,

there seems to be a bug with the handling of variable declarations around function calls with arrays as return values.
I get different leakages for the attached programs, where the only difference is on line 13 / 14: 
- Result is correct if the variable ``l`` is declared and assigned in a single statement
- Result is incorrect if the variable is first declared, then assigned in a separate statement.

As far as I could tell, the error only occurs with the combination of function call + array as return value + return value packed in tuple.

[incorrect_leakage.nd.txt](https://github.com/parttimenerd/nildumu/files/6566799/incorrect_leakage.nd.txt)
[correct_leakage.nd.txt](https://github.com/parttimenerd/nildumu/files/6566800/correct_leakage.nd.txt)

**Comment by parttimenerd** [comment]
```java
bit_width 2;

h input int h = 0buu;
int[1] b;

b= *({h},);
int l; /* declared then assigned */
l = b[0];

int k = b[0] /* declared and directly assigned */

l output int o = l | 0b01;
l output int p = k | 0b10;
```
Results in
```java
use_sec basic;
bit_width 2;
int __bl_b_01;
h input int h = 0buu;
int __bl_b_0;
{
  int __bl___bl__0 = h;
  __bl_b_01 = __bl___bl__0;
}
int l;
l = __bl_b_0; /* incorrect */
int k = __bl_b_01; /* correct */
l output int o = (l | 1);
l output int p = (k | ((0 + ~0b010) + 1));
```
Preprocessing is hard…
